-- 코드를 입력하세요
WITH SUB AS (
    SELECT MAX(FAVORITES) AS FAVORITES FROM REST_INFO
    GROUP BY FOOD_TYPE
    ORDER BY FOOD_TYPE DESC
)

SELECT FOOD_TYPE, REST_ID, REST_NAME, s.FAVORITES FROM REST_INFO r
INNER JOIN SUB s ON r.FAVORITES = s.FAVORITES
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC