-- 코드를 입력하세요
SELECT YEAR(o.SALES_DATE) AS YEAR,
    MONTH(o.SALES_DATE) AS MONTH,
    u.GENDER,
    COUNT(DISTINCT u.USER_ID) AS USERS
    FROM USER_INFO u
INNER JOIN ONLINE_SALE o on u.USER_ID = o.USER_ID
WHERE u.gender IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3