-- 코드를 입력하세요
WITH a AS (
    SELECT ID, NAME, HOST_ID, COUNT(*) AS COUNT FROM PLACES
    GROUP BY HOST_ID
)

SELECT p.ID, p.NAME, p.HOST_ID FROM a
INNER JOIN PLACES p ON a.HOST_ID = p.HOST_ID
WHERE COUNT >= 2